name: 'autoupdate-dependencies'
description: 'Automatic dependencies update'
inputs:
  token:
    description: Token used to send pull requests
    required: true
  update-command:
    description: Command to update dependencies and do initial checks
    required: true
  update-path:
    description: Path to directory to run the update-command. If not provided defaults to root
    required: false
runs:
  using: 'composite'
  steps:
     - run: ./autoupdate-dependencies.sh ${{ inputs.token }} ${{ inputs.update-command }} ${{ inputs.update-path }}
       shell: bash
